name: Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Newman (if not already installed)
        run: npm install -g newman  # Replace with your installation command if needed

      - name: Run Postman Tests and Capture Output
        run: |
          newman run newmanCollection.json &> output.log

      - name: Send Postman Test Results to Telegram using Telegram CLI (Optional)
        # Requires pre-installation and configuration of 'telegram-cli'
        run: |
          # Access secrets directly within the run command block
          telegram-cli -k ${{ secrets.BOT_TOKEN }} \
            sendDocument ${{ github.workspace }}/output.log \
            --chat_id ${{ secrets.CHAT_ID }} \
            --caption "Postman Test Results: ${{ job.status }}"

      - name: Upload Test Results Artifact (Optional - for backup)
        uses: actions/upload-artifact@v4
        with:
          name: test-results  # Optional - upload for backup purposes
          path: output.log
