name: Postman Tests with Telegram Notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests and Capture Output
        run: |
          newman run newmanCollection.json &> output.log

      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: output.log

      - name: Send Test Results to Telegram
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.7341585544:AAEwPxTXW6JjVsixhrUa7c0RY06FoDmq_6c }}/sendMessage \
            -d chat_id=${{ secrets.7341585544 }} \
            -d text="Test Results: ${{ job.status }} \n**See output log for details:** [output.log](https://github.com/khasan/postman/actions/runs/850690a2682750487f893ac9fb1b1b359af7ab87/logs)"
          # Remove the leading '-' (dash) before 'run'
