name: Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run newmanCollection.json

      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: output.log  # Assuming output.log is generated during tests
