name: Postman Tests with Telegram Notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests and Capture Output
        run: |
          newman run newmanCollection.json &> output.log

      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: output.log

      - name: Send Test Results to Telegram
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.CHAT_ID }} \
            -d text="Test Results: ${{ job.status }} \n**See output log for details:** [output.log](https://github.com/<username>/<repository>/actions/runs/<run_id>/logs)"
          # Remove the leading '-' (dash) before 'run'
