name: Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Run Tests
        uses: grabblicious/postman-collection@v2
        with:
          collection: newmanCollection.json

      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: output.log
