name: Postman Tests with Telegram Notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ... your existing test execution steps ...

      - name: Upload Test Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: output.log  # Replace with your test results file path

      - name: Download Test Results Artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Process and Format Results
        run: |
          # Download the test results (assuming downloaded to 'output.log')
          TEST_RESULTS=$(cat output.log)  # Replace with your processing command

          # Extract key information from results (modify as needed)
          TEST_STATUS=$(echo "$TEST_RESULTS" | grep 'summary' | awk '{print $NF}')  # Replace with your extraction logic
          PASSED_TESTS=$(echo "$TEST_RESULTS" | grep 'passed' | wc -l)  # Replace with your extraction logic
          FAILED_TESTS=$(echo "$TEST_RESULTS" | grep 'failed' | wc -l)  # Replace with your extraction logic

      - name: Send Test Results to Telegram
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.CHAT_ID }} \
            -d text="Test Results: $TEST_STATUS \n**Passed:** $PASSED_TESTS, **Failed:** $FAILED_TESTS \n**See full log for details:** [output.log](https://github.com/<username>/<repository>/actions/runs/<run_id>/logs)"
