name: Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests and Capture Output
        run: newman run newmanCollection.json &> output.log

      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: output.log

      - name: Send results to Telegram Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -F "chat_id=${CHAT_ID}" -F document=@output.log https://api.telegram.org/bot${BOT_TOKEN}/sendDocument
